@startuml

actor User
participant ":ParserManager"
participant ":RecommendParser"
participant ":RecommendCommand"
participant ":Ui"
participant ":ExceptionHandler"

User -> ":ParserManager": parse("recommend <muscle_group>")
activate ":ParserManager"

":ParserManager" -> ":RecommendParser": parse("recommend <muscle_group>")
activate ":RecommendParser"

alt valid input
    create ":RecommendCommand"
    ":RecommendParser" -> ":RecommendCommand": new RecommendCommand(list)
    activate ":RecommendCommand"

    ":RecommendCommand" -> ":RecommendCommand": execute()
    activate ":RecommendCommand"
    ":RecommendCommand" --> ":RecommendCommand" : return
    deactivate ":RecommendCommand"

    ":RecommendCommand" -> ":Ui": printMessage(list)
    activate ":Ui"
    ":Ui" --> ":RecommendCommand": display message
    deactivate ":Ui"

    ":RecommendCommand" --> ":RecommendParser": success message
    deactivate ":RecommendCommand"

    ":RecommendParser" --> ":ParserManager": success message
    'deactivate ":RecommendParser"

    ":ParserManager" --> User: success message
    'deactivate ":ParserManager"

else invalid input
    ":RecommendParser" -> ":ExceptionHandler": throw exception
    activate ":ExceptionHandler"
    ":ExceptionHandler" --> ":RecommendParser": error message
    deactivate ":ExceptionHandler"

    ":RecommendParser" --> ":ParserManager": error message
    deactivate ":RecommendParser"

    ":ParserManager" --> User: error message
    deactivate ":ParserManager"
end

@enduml
