@startuml
'autonumber adds numbering to calls
autonumber

/' for now i put as alt for valid input and invalid input'/
/' but idk if i shoukd be splitting it into the respective muscle groups and their respective outputs'/
/' can u have multiple boxes for alt? is not limited to 2 paths rye - need to ask cf'/

actor User
participant "RecommendParser" as Parser
participant "RecommendCommand"
participant "Ui"
participant "ExceptionHandler\n(HealthBudException / InvalidRecommendException)"

User -> Parser: parse("recommend chest")

alt valid input
    Parser -> RecommendCommand: new RecommendCommand(list)
    Parser --> User: RecommendCommand
    User -> RecommendCommand: execute()
    RecommendCommand -> Ui: printMessage(list)
else invalid input
    Parser -> ExceptionHandler: throw InvalidRecommendException / HealthBudException
end

@enduml

