@startuml
'https://plantuml.com/class-diagram

abstract class Command {
    +execute(LogList goalLogs, LogList pbLogs, LogList mealLogs, LogList workoutLogs,
             LogList waterLogs, LogList cardioLogs, String input)
}

class RecommendCommand {
    +execute(LogList goalLogs, LogList pbLogs, LogList mealLogs, LogList workoutLogs,
                          LogList waterLogs, LogList cardioLogs, String input)
    +getRecommendation(input: String): String
}

Command <|-- RecommendCommand

class Parser {
    +handleInput(...)
}

Parser --> RecommendCommand : creates

class LogList

class InvalidRecommendException
class HealthBudException

RecommendCommand ..> LogList
RecommendCommand ..> InvalidRecommendException
RecommendCommand ..> HealthBudException

@enduml